### ISSUE TITLE
add a Webpage Icon for searchcaster.xyz

### ISSUE THREAD

**Issue by prood** [gskril/searchcaster#23]
Reason: the app icon looks better when Added to Home Screen on iOS

Output: have an icon file in the root document folder after building

Possible implementation: reference `searchcaster/public/img/logo.png` in `build-manifest.json`. After building, it would also be available as `apple-touch-icon.png` in the root folder along with `index.html`

Reference: [Configuring Web Applications](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html)

**Comment by gskril** [comment]
Thanks for flagging! This used to work and then I guess at some point I renamed the image file 😅. Fixed in https://github.com/gskril/searchcaster/commit/0250041529dab2f3c442739df2bc1f1301982e6d
